//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LicenseApplication.Models
{
    using System;
    using System.ComponentModel.DataAnnotations;
    using System.Collections.Generic;
    
    public partial class User
    {        
        public int Id { get; set; }

        [Required]
        [EmailAddress]
        [StringLength(150)]
        [Display(Name = "Email ID : ")]
        public string EmailID { get; set; }

        [Required]
        [DataType(DataType.Password)]
        [StringLength(256, MinimumLength = 8)]
        [Display(Name = "Password : ")]
        public string Password { get; set; }

        [Required]
        [StringLength(30)]
        [Display(Name = "First Name : ")]
        public string First_Name { get; set; }

        [StringLength(30)]
        [Display(Name = "Last Name : ")]
        public string Last_Name { get; set; }

        [Required]
        [StringLength(30)]
        [Display(Name = "Display Name : ")]
        public string Display_Name { get; set; }

        [Required]
        [DataType(DataType.DateTime)]
        [Display(Name = "Joined Date : ")]
        public System.DateTime Joined_Date { get; set; }

        [Required]
        [DataType(DataType.DateTime)]
        [Display(Name = "Last Login : ")]
        public System.DateTime Last_Login { get; set; }
    }
}
